name: Release

on:
  push:
    tags:
      - v*

jobs:
  publishNpm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF##*/v})
    - run: yarn install
      working-directory: typescript-client
    - run: yarn bootstrap
      working-directory: typescript-client
    - name: Update package version
      run: yarn set-version ${PACKAGE_VERSION}
      working-directory: typescript-client
      env:
        PACKAGE_VERSION: ${{ steps.tag.outputs.VERSION }}
    - run: yarn build
      working-directory: typescript-client
    - run: yarn publish-packages
      working-directory: typescript-client
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
  
  publishNuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF##*/v})
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        version: ${{ steps.tag.outputs.VERSION }}
    # Publish SqlToExpression nuget
    - name: publish on version change
      id: publish_nuget_sqltoexpression
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.SqlToExpression/Koralium.SqlToExpression.csproj
        PACKAGE_NAME: Koralium.SqlToExpression
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    
    # Publish Koralium.Shared
    - name: publish on version change
      id: publish_nuget_shared
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.Shared/Koralium.Shared.csproj
        PACKAGE_NAME: Koralium.Shared
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish on version change
      id: publish_nuget_koralium
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium/Koralium.csproj
        PACKAGE_NAME: Koralium
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}

    - name: publish on version change
      id: publish_nuget_json
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.Transport.Json/Koralium.Transport.Json.csproj
        PACKAGE_NAME: Koralium.Json
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish sqlparser
      id: publish_nuget_sqlparser
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.SqlParser/Koralium.SqlParser.csproj
        PACKAGE_NAME: Koralium.SqlParser
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish sqlparser ANTLR
      id: publish_nuget_sqlparser_antlr
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.SqlParser.ANTLR/Koralium.SqlParser.ANTLR.csproj
        PACKAGE_NAME: Koralium.SqlParser.ANTLR
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish Core
      id: publish_nuget_koralium_core
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.Core/Koralium.Core.csproj
        PACKAGE_NAME: Koralium.SqlParser.ANTLR
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish Transport
      id: publish_nuget_koralium_transport
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.Transport/Koralium.Transport.csproj
        PACKAGE_NAME: Koralium.SqlParser.ANTLR
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish Transport Arrow Flight
      id: publish_nuget_koralium_transport_arrowflight
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.Transport.ArrowFlight/Koralium.Transport.ArrowFlight.csproj
        PACKAGE_NAME: Koralium.SqlParser.ANTLR
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish Transport RowLevelSecurity
      id: publish_nuget_koralium_transport_rowlevelsecurity
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.Transport.RowLevelSecurity/Koralium.Transport.RowLevelSecurity.csproj
        PACKAGE_NAME: Koralium.Transport.RowLevelSecurity
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish Transport LegacyGrpc
      id: publish_nuget_koralium_transport_legacygrpc
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.Transport.LegacyGrpc/Koralium.Transport.LegacyGrpc.csproj
        PACKAGE_NAME: Koralium.Transport.LegacyGrpc
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish Transport LegacyGrpc Abstractions
      id: publish_nuget_koralium_transport_legacygrpc_abstractions
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.Transport.LegacyGrpc.Abstractions/Koralium.Transport.LegacyGrpc.Abstractions.csproj
        PACKAGE_NAME: Koralium.Transport.LegacyGrpc.Abstractions
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish Data Arrow Flight
      id: publish_nuget_koralium_data_arrowflight
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.Data.ArrowFlight/Koralium.Data.ArrowFlight.csproj
        PACKAGE_NAME: Koralium.Data.ArrowFlight
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish EntityFrameworkCore Arrow Flight
      id: publish_nuget_koralium_entityframeworkcore_arrowflight
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.EntityFrameworkCore.ArrowFlight/Koralium.EntityFrameworkCore.ArrowFlight.csproj
        PACKAGE_NAME: Koralium.EntityFrameworkCore.ArrowFlight
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}

