name: .NET Core

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF##*/v})
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200

      # Publish
    - name: Echo
      run: echo ${{ steps.tag.outputs.VERSION }}
