name: Release

on:
  push:
    tags:
      - v*

jobs:
  publishNpm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
      working-directory: typescript-client
    - run: npm publish --access public
      working-directory: typescript-client
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
  
  publishNuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF##*/v})
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        version: ${{ steps.tag.outputs.VERSION }}
    # Publish SqlToExpression nuget
    - name: publish on version change
      id: publish_nuget_sqltoexpression
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.SqlToExpression/Koralium.SqlToExpression.csproj
        PACKAGE_NAME: Koralium.SqlToExpression
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    
    # Publish Koralium.Shared
    - name: publish on version change
      id: publish_nuget_shared
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium.Shared/Koralium.Shared.csproj
        PACKAGE_NAME: Koralium.Shared
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}
    - name: publish on version change
      id: publish_nuget_koralium
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: netcore/src/Koralium/Koralium.csproj
        PACKAGE_NAME: Koralium
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.tag.outputs.VERSION }}

